[build]
command = "npx tsc"
functions = "dist"
publish = "public"
environment = { URL_FFVB = "https://www.ffvbbeach.org/ffvbapp/resu/vbspo_calendrier.php" }

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/index/:splat"
status = 200
force = true